# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1324, 569)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.tabWidget.setMouseTracking(True)
        self.tabWidget.setObjectName("tabWidget")
        self.stutab_2 = QtWidgets.QWidget()
        self.stutab_2.setObjectName("stutab_2")
        self.stutab = QtWidgets.QTableWidget(self.stutab_2)
        self.stutab.setGeometry(QtCore.QRect(10, 130, 1281, 371))
        self.stutab.setObjectName("stutab")
        self.stutab.setColumnCount(10)
        self.stutab.setRowCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.stutab.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.stutab.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.stutab.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.stutab.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.stutab.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.stutab.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.stutab.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.stutab.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.stutab.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.stutab.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.stutab.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.stutab.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.stutab.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.stutab.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.stutab.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.stutab.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.stutab.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.stutab.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.stutab.setHorizontalHeaderItem(9, item)
        self.label_2 = QtWidgets.QLabel(self.stutab_2)
        self.label_2.setGeometry(QtCore.QRect(250, 30, 91, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.stutab_2)
        self.label_3.setGeometry(QtCore.QRect(40, 80, 58, 21))
        self.label_3.setObjectName("label_3")
        self.stucom = QtWidgets.QComboBox(self.stutab_2)
        self.stucom.setGeometry(QtCore.QRect(140, 30, 80, 22))
        self.stucom.setObjectName("stucom")
        self.stucom.addItem("")
        self.stucom.addItem("")
        self.stucom.addItem("")
        self.stucom.addItem("")
        self.stucom.addItem("")
        self.stucom.addItem("")
        self.stucom_2 = QtWidgets.QComboBox(self.stutab_2)
        self.stucom_2.setGeometry(QtCore.QRect(350, 30, 80, 22))
        self.stucom_2.setObjectName("stucom_2")
        self.stucom_2.addItem("")
        self.stucom_2.addItem("")
        self.stucom_2.addItem("")
        self.stucom_2.addItem("")
        self.stucom_2.addItem("")
        self.stusearedit = QtWidgets.QLineEdit(self.stutab_2)
        self.stusearedit.setGeometry(QtCore.QRect(100, 80, 211, 22))
        self.stusearedit.setObjectName("stusearedit")
        self.stusearch = QtWidgets.QPushButton(self.stutab_2)
        self.stusearch.setGeometry(QtCore.QRect(340, 80, 93, 28))
        self.stusearch.setObjectName("stusearch")
        self.sturadd = QtWidgets.QPushButton(self.stutab_2)
        self.sturadd.setGeometry(QtCore.QRect(490, 0, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.sturadd.setFont(font)
        self.sturadd.setObjectName("sturadd")
        self.stuedit = QtWidgets.QPushButton(self.stutab_2)
        self.stuedit.setGeometry(QtCore.QRect(490, 30, 93, 28))
        self.stuedit.setObjectName("stuedit")
        self.studelet = QtWidgets.QPushButton(self.stutab_2)
        self.studelet.setGeometry(QtCore.QRect(490, 60, 93, 28))
        self.studelet.setObjectName("studelet")
        self.label_8 = QtWidgets.QLabel(self.stutab_2)
        self.label_8.setGeometry(QtCore.QRect(40, 30, 91, 16))
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.stutab_2)
        self.label_10.setGeometry(QtCore.QRect(630, 10, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.stuupedit = QtWidgets.QLineEdit(self.stutab_2)
        self.stuupedit.setGeometry(QtCore.QRect(770, 10, 211, 31))
        self.stuupedit.setObjectName("stuupedit")
        self.stusearview = QtWidgets.QPushButton(self.stutab_2)
        self.stusearview.setGeometry(QtCore.QRect(1000, 10, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.stusearview.setFont(font)
        self.stusearview.setObjectName("stusearview")
        self.label_11 = QtWidgets.QLabel(self.stutab_2)
        self.label_11.setGeometry(QtCore.QRect(630, 70, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.stuedit_2 = QtWidgets.QLineEdit(self.stutab_2)
        self.stuedit_2.setGeometry(QtCore.QRect(770, 70, 211, 31))
        self.stuedit_2.setObjectName("stuedit_2")
        self.stuupdate = QtWidgets.QPushButton(self.stutab_2)
        self.stuupdate.setGeometry(QtCore.QRect(1150, 10, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.stuupdate.setFont(font)
        self.stuupdate.setObjectName("stuupdate")
        self.stuupdate_2 = QtWidgets.QPushButton(self.stutab_2)
        self.stuupdate_2.setGeometry(QtCore.QRect(1150, 70, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.stuupdate_2.setFont(font)
        self.stuupdate_2.setObjectName("stuupdate_2")
        self.stusearview_2 = QtWidgets.QPushButton(self.stutab_2)
        self.stusearview_2.setGeometry(QtCore.QRect(1000, 70, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.stusearview_2.setFont(font)
        self.stusearview_2.setObjectName("stusearview_2")
        self.subfuction = QtWidgets.QPushButton(self.stutab_2)
        self.subfuction.setGeometry(QtCore.QRect(490, 90, 93, 28))
        self.subfuction.setObjectName("subfuction")
        self.tabWidget.addTab(self.stutab_2, "")
        self.teatab_2 = QtWidgets.QWidget()
        self.teatab_2.setObjectName("teatab_2")
        self.teasearedit = QtWidgets.QLineEdit(self.teatab_2)
        self.teasearedit.setGeometry(QtCore.QRect(230, 20, 211, 22))
        self.teasearedit.setObjectName("teasearedit")
        self.teasearch = QtWidgets.QPushButton(self.teatab_2)
        self.teasearch.setGeometry(QtCore.QRect(450, 20, 93, 28))
        self.teasearch.setObjectName("teasearch")
        self.label_20 = QtWidgets.QLabel(self.teatab_2)
        self.label_20.setGeometry(QtCore.QRect(110, 20, 121, 21))
        self.label_20.setObjectName("label_20")
        self.teatab = QtWidgets.QTableWidget(self.teatab_2)
        self.teatab.setGeometry(QtCore.QRect(10, 130, 1281, 371))
        self.teatab.setObjectName("teatab")
        self.teatab.setColumnCount(10)
        self.teatab.setRowCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.teatab.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.teatab.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.teatab.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.teatab.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.teatab.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.teatab.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.teatab.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.teatab.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.teatab.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.teatab.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.teatab.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.teatab.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.teatab.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.teatab.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.teatab.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.teatab.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.teatab.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.teatab.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.teatab.setHorizontalHeaderItem(9, item)
        self.teaadd = QtWidgets.QPushButton(self.teatab_2)
        self.teaadd.setGeometry(QtCore.QRect(110, 70, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.teaadd.setFont(font)
        self.teaadd.setObjectName("teaadd")
        self.teaedit = QtWidgets.QPushButton(self.teatab_2)
        self.teaedit.setGeometry(QtCore.QRect(250, 70, 93, 28))
        self.teaedit.setObjectName("teaedit")
        self.teadelet = QtWidgets.QPushButton(self.teatab_2)
        self.teadelet.setGeometry(QtCore.QRect(390, 70, 93, 28))
        self.teadelet.setObjectName("teadelet")
        self.label_31 = QtWidgets.QLabel(self.teatab_2)
        self.label_31.setGeometry(QtCore.QRect(600, 20, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.teaupedit = QtWidgets.QLineEdit(self.teatab_2)
        self.teaupedit.setGeometry(QtCore.QRect(770, 20, 211, 31))
        self.teaupedit.setObjectName("teaupedit")
        self.teasearview = QtWidgets.QPushButton(self.teatab_2)
        self.teasearview.setGeometry(QtCore.QRect(1000, 20, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.teasearview.setFont(font)
        self.teasearview.setObjectName("teasearview")
        self.teaupdate = QtWidgets.QPushButton(self.teatab_2)
        self.teaupdate.setGeometry(QtCore.QRect(1150, 20, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.teaupdate.setFont(font)
        self.teaupdate.setObjectName("teaupdate")
        self.tabWidget.addTab(self.teatab_2, "")
        self.watertab = QtWidgets.QWidget()
        self.watertab.setObjectName("watertab")
        self.label_4 = QtWidgets.QLabel(self.watertab)
        self.label_4.setGeometry(QtCore.QRect(40, 40, 241, 41))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 16000000))
        self.label_4.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.watertab)
        self.label_5.setGeometry(QtCore.QRect(40, 110, 221, 41))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 16000000))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.watertab)
        self.label_6.setGeometry(QtCore.QRect(60, 180, 251, 41))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 16000000))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.watertab)
        self.label_7.setGeometry(QtCore.QRect(40, 250, 271, 41))
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 16000000))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.startdate = QtWidgets.QLineEdit(self.watertab)
        self.startdate.setGeometry(QtCore.QRect(290, 40, 261, 41))
        self.startdate.setObjectName("startdate")
        self.enddate = QtWidgets.QLineEdit(self.watertab)
        self.enddate.setGeometry(QtCore.QRect(290, 110, 261, 41))
        self.enddate.setObjectName("enddate")
        self.excelpath = QtWidgets.QLineEdit(self.watertab)
        self.excelpath.setGeometry(QtCore.QRect(290, 180, 261, 41))
        self.excelpath.setObjectName("excelpath")
        self.dataedit = QtWidgets.QLineEdit(self.watertab)
        self.dataedit.setGeometry(QtCore.QRect(290, 250, 261, 41))
        self.dataedit.setObjectName("dataedit")
        self.calculate = QtWidgets.QPushButton(self.watertab)
        self.calculate.setGeometry(QtCore.QRect(40, 330, 511, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.calculate.setFont(font)
        self.calculate.setObjectName("calculate")
        self.startdatewidge = QtWidgets.QCalendarWidget(self.watertab)
        self.startdatewidge.setEnabled(True)
        self.startdatewidge.setGeometry(QtCore.QRect(560, 40, 296, 229))
        self.startdatewidge.setMouseTracking(False)
        self.startdatewidge.setInputMethodHints(QtCore.Qt.ImhNone)
        self.startdatewidge.setGridVisible(False)
        self.startdatewidge.setSelectionMode(QtWidgets.QCalendarWidget.SingleSelection)
        self.startdatewidge.setHorizontalHeaderFormat(QtWidgets.QCalendarWidget.ShortDayNames)
        self.startdatewidge.setVerticalHeaderFormat(QtWidgets.QCalendarWidget.NoVerticalHeader)
        self.startdatewidge.setNavigationBarVisible(True)
        self.startdatewidge.setDateEditEnabled(True)
        self.startdatewidge.setDateEditAcceptDelay(1500)
        self.startdatewidge.setObjectName("startdatewidge")
        self.startbutton = QtWidgets.QToolButton(self.watertab)
        self.startbutton.setGeometry(QtCore.QRect(510, 40, 41, 41))
        self.startbutton.setObjectName("startbutton")
        self.endbutton = QtWidgets.QToolButton(self.watertab)
        self.endbutton.setGeometry(QtCore.QRect(510, 110, 41, 41))
        self.endbutton.setObjectName("endbutton")
        self.excelbutton = QtWidgets.QToolButton(self.watertab)
        self.excelbutton.setGeometry(QtCore.QRect(510, 180, 41, 41))
        self.excelbutton.setObjectName("excelbutton")
        self.enddatewidge = QtWidgets.QCalendarWidget(self.watertab)
        self.enddatewidge.setGeometry(QtCore.QRect(560, 110, 296, 229))
        self.enddatewidge.setObjectName("enddatewidge")
        self.tabWidget.addTab(self.watertab, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.stutab.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.stutab.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.stutab.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.stutab.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.stutab.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.stutab.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.stutab.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.stutab.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.stutab.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "10"))
        item = self.stutab.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "SchoolID"))
        item = self.stutab.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Identity"))
        item = self.stutab.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Name"))
        item = self.stutab.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Gender"))
        item = self.stutab.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "CardID"))
        item = self.stutab.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Class"))
        item = self.stutab.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Weight"))
        item = self.stutab.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "DailyShouldDrink"))
        item = self.stutab.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Height"))
        item = self.stutab.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Number"))
        self.label_2.setText(_translate("MainWindow", "選擇班級:"))
        self.label_3.setText(_translate("MainWindow", "學號:"))
        self.stucom.setItemText(0, _translate("MainWindow", "All"))
        self.stucom.setItemText(1, _translate("MainWindow", "七年級"))
        self.stucom.setItemText(2, _translate("MainWindow", "八年級"))
        self.stucom.setItemText(3, _translate("MainWindow", "九年級"))
        self.stucom.setItemText(4, _translate("MainWindow", "教職員"))
        self.stucom.setItemText(5, _translate("MainWindow", "Alumni"))
        self.stucom_2.setItemText(0, _translate("MainWindow", "All"))
        self.stucom_2.setItemText(1, _translate("MainWindow", "一班"))
        self.stucom_2.setItemText(2, _translate("MainWindow", "二班"))
        self.stucom_2.setItemText(3, _translate("MainWindow", "三班"))
        self.stucom_2.setItemText(4, _translate("MainWindow", "四班"))
        self.stusearch.setText(_translate("MainWindow", "查詢"))
        self.sturadd.setText(_translate("MainWindow", "新增"))
        self.stuedit.setText(_translate("MainWindow", "編輯"))
        self.studelet.setText(_translate("MainWindow", "刪除"))
        self.label_8.setText(_translate("MainWindow", "選擇年級:"))
        self.label_10.setText(_translate("MainWindow", "學生批量資料更新 :"))
        self.stusearview.setText(_translate("MainWindow", "選擇檔案並預覽"))
        self.label_11.setText(_translate("MainWindow", "學生年級資料更新:"))
        self.stuupdate.setText(_translate("MainWindow", "檢驗格式並更新"))
        self.stuupdate_2.setText(_translate("MainWindow", "檢驗格式並更新"))
        self.stusearview_2.setText(_translate("MainWindow", "選擇檔案並預覽"))
        self.subfuction.setText(_translate("MainWindow", "新增卡號"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.stutab_2), _translate("MainWindow", "學生資料管理"))
        self.teasearch.setText(_translate("MainWindow", "查詢"))
        self.label_20.setText(_translate("MainWindow", "教職員代碼查詢:"))
        item = self.teatab.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.teatab.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.teatab.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.teatab.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.teatab.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.teatab.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.teatab.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.teatab.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.teatab.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "10"))
        item = self.teatab.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "SchoolID"))
        item = self.teatab.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Identity"))
        item = self.teatab.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Name"))
        item = self.teatab.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Gender"))
        item = self.teatab.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "CardID"))
        item = self.teatab.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Class"))
        item = self.teatab.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Weight"))
        item = self.teatab.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "DailyShouldDrink"))
        item = self.teatab.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Height"))
        item = self.teatab.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Number"))
        self.teaadd.setText(_translate("MainWindow", "新增"))
        self.teaedit.setText(_translate("MainWindow", "編輯"))
        self.teadelet.setText(_translate("MainWindow", "刪除"))
        self.label_31.setText(_translate("MainWindow", "教職員批量資料更新 :"))
        self.teasearview.setText(_translate("MainWindow", "選擇檔案並預覽"))
        self.teaupdate.setText(_translate("MainWindow", "檢驗格式並更新"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.teatab_2), _translate("MainWindow", "教職員資料管理"))
        self.label_4.setText(_translate("MainWindow", "資料統計起始日期 :"))
        self.label_5.setText(_translate("MainWindow", "資料統計結束日期 :"))
        self.label_6.setText(_translate("MainWindow", "Excel檔存檔路徑 :"))
        self.label_7.setText(_translate("MainWindow", "每日資料採計閥值 :"))
        self.calculate.setText(_translate("MainWindow", "Calculate"))
        self.startbutton.setText(_translate("MainWindow", "..."))
        self.endbutton.setText(_translate("MainWindow", "..."))
        self.excelbutton.setText(_translate("MainWindow", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.watertab), _translate("MainWindow", "飲水報表產生器"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

